// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7iWeGj6p6_iD2ewJ-zUz2rFr7GpjMvI8',
    appId: '1:917188795131:web:71c5a2a27c234e4becae5e',
    messagingSenderId: '917188795131',
    projectId: 'movies-9fa3a',
    authDomain: 'movies-9fa3a.firebaseapp.com',
    storageBucket: 'movies-9fa3a.firebasestorage.app',
    measurementId: 'G-ZZ79N7BK55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWa8zwhuIU421ZIBIY9wIoO2Mv9gooey8',
    appId: '1:917188795131:android:67d66409bcae6dceecae5e',
    messagingSenderId: '917188795131',
    projectId: 'movies-9fa3a',
    storageBucket: 'movies-9fa3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtnBaZ07-6d5mF38rUU8YiSJnUcu7c98E',
    appId: '1:917188795131:ios:d6bf05c4e39502a6ecae5e',
    messagingSenderId: '917188795131',
    projectId: 'movies-9fa3a',
    storageBucket: 'movies-9fa3a.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtnBaZ07-6d5mF38rUU8YiSJnUcu7c98E',
    appId: '1:917188795131:ios:d6bf05c4e39502a6ecae5e',
    messagingSenderId: '917188795131',
    projectId: 'movies-9fa3a',
    storageBucket: 'movies-9fa3a.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7iWeGj6p6_iD2ewJ-zUz2rFr7GpjMvI8',
    appId: '1:917188795131:web:01d75cccb428aecaecae5e',
    messagingSenderId: '917188795131',
    projectId: 'movies-9fa3a',
    authDomain: 'movies-9fa3a.firebaseapp.com',
    storageBucket: 'movies-9fa3a.firebasestorage.app',
    measurementId: 'G-N76EF8Y8BW',
  );
}
